from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .models import Player, Score
from .serializers import PlayerSerializer, ScoreSerializer

# --- 1. REGISTER PLAYER ---
@api_view(['POST'])
def register_player(request):
    """
    Expects JSON: { "username": "SaanpKing" }
    Returns JSON: { "username": "SaanpKing", "player_code": "A1B2", ... }
    """
    username = request.data.get('username')
    
    if not username:
        return Response({"error": "Username is required"}, status=status.HTTP_400_BAD_REQUEST)

    # Create the player (code is auto-generated by model)
    player = Player.objects.create(username=username)
    
    serializer = PlayerSerializer(player)
    return Response(serializer.data, status=status.HTTP_201_CREATED)

# --- 2. SUBMIT SCORE ---
@api_view(['POST'])
def submit_score(request):
    """
    Expects JSON: { "player_code": "A1B2", "score": 500 }
    """
    player_code = request.data.get('player_code')
    points = request.data.get('score')

    if not player_code or points is None:
        return Response({"error": "Player code and score are required"}, status=status.HTTP_400_BAD_REQUEST)

    try:
        player = Player.objects.get(player_code=player_code)
    except Player.DoesNotExist:
        return Response({"error": "Invalid player code"}, status=status.HTTP_404_NOT_FOUND)

    # Save the score
    Score.objects.create(player=player, points=points)
    
    return Response({"message": "Score submitted successfully"}, status=status.HTTP_201_CREATED)

# --- 3. GET GLOBAL LEADERBOARD ---
@api_view(['GET'])
def get_leaderboard(request):
    """
    Returns top 10 scores globally.
    """
    # Get top 10 scores ordered by points descending
    top_scores = Score.objects.select_related('player').order_by('-points')[:10]
    serializer = ScoreSerializer(top_scores, many=True)
    return Response(serializer.data)

# --- 4. GET PLAYER RECENT SCORES ---
@api_view(['GET'])
def get_player_history(request, player_code):
    """
    Returns the last 10 scores for a specific player.
    """
    try:
        player = Player.objects.get(player_code=player_code)
    except Player.DoesNotExist:
        return Response({"error": "Invalid player code"}, status=status.HTTP_404_NOT_FOUND)

    # Get recent scores for this player
    recent_scores = Score.objects.filter(player=player).order_by('-played_at')[:10]
    serializer = ScoreSerializer(recent_scores, many=True)
    return Response(serializer.data)